import pyautogui as at

at.sleep(10)
at.hotkey('ctrl', 'alt', '1')
at.sleep(5)
at.click(x=646, y=519)
at.sleep(2)
at.hotkey('ctrl', 'num1')
at.hotkey('ctrl', 'num2')
at.hotkey('ctrl', 'num3')
at.hotkey('ctrl', 'num4')
at.hotkey('ctrl', 'num5')
at.hotkey('ctrl', 'e')
at.sleep(2)
at.write('n')
at.hotkey('enter')
at.sleep(5)
at.hotkey('ctrl', 't')
at.write('u')
at.hotkey('enter')
at.sleep(5)
at.moveTo(x=1304, y=170)
at.moveTo(x=1177, y=318)
at.click(x=1177, y=318)
at.sleep(5)
at.click()
at.sleep(3)
at.scroll(-505)
at.sleep(3)
at.hotkey('ctrl', 't')
at.click(x=1217, y=50)
